name: mea #TODO Replace with you app's name
description: Mea project #TODO Replace with you app's description
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  google_fonts: 6.1.0
  dio: ^5.3.0
  dio_cache_interceptor: ^3.4.2
  dio_http2_adapter: ^2.3.1
  envied: ^0.5.2
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+6
  firebase_performance_dio: ^0.6.0
  shared_preferences: ^2.2.2
  awesome_dialog: ^3.1.0
  extended_image: ^8.0.0
  extended_image_library: ^3.5.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  # dart run flutter_native_splash:create
  # stream_chat_flutter: $latest_version
  photo_manager: ^2.8.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^12.1.1
  json_serializable: ^6.7.1
  package_info_plus: ^4.0.0
  pretty_dio_logger: ^1.3.1
  custom_sliding_segmented_control: ^1.8.1
  gap: ^3.0.1
  flutter_local_notifications: ^16.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  stream_chat_flutter: ^6.11.0
  stream_chat_flutter_core: ^6.10.0
  stream_chat: ^6.9.0

dev_dependencies:
  build_runner: ^2.4.6
  # dart run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # dart run change_app_package_name:main <com.new.package.name>
  envied_generator: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_launcher_icons:main
  flutter_test:
    sdk: flutter
  #flutter_driver:
  #sdk: flutter
  freezed: ^2.4.1
  very_good_analysis: ^5.0.0+1
  # screenshots: ^2.1.1
  # screenshots
  # test: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
